language: node_js
node_js: 
  - "stable"
services:
  - postgresql
cache:
  yarn: true
  directories:
    - "node_modules"
before_script:
  - psql -c 'create database testdb;' -U postgres
env:
  - DATABASE_URL=postgres://postgres:postgres@127.0.0.1/testdb